### ISSUE TITLE
Form Authentication

### ISSUE THREAD

**Issue by zagub59** [MinecraftJohn/wifi-connect#7]
Hi John,

Thank you for your work and to share it with the world ! 

I'm currently testing it and I can't find out how to make it work with form authentication. I only have basic coding skills so please apologize for my lack of knowledge but it seems as this option is missing from your index.html.

I've read the 5.4.6 and 5.9.9 Omada API documentations and as far as I understand it, the integer auth type 11 would be the form auth type but I am not enough skilled to add the option to your code.

What I'd like to do is to allow authentication by asking guests to type an e-mail address and to send data to the corresponding form in Omada.

Could you by any chance guide me / help me on this ?

Keep up the good work !

**Comment by MinecraftJohn** [comment]
Hi, I'm not familiar with backend stuffs I'm afraid I can't assist you properly with that. However maybe this code is what your looking for:
![image](https://github.com/MinecraftJohn/wifi-connect/assets/84890923/5b6e6a72-07ae-40b2-adc3-b92a232a2511)
you can't see that element live when viewing the page because I hid it since this project only use hotspot type: Voucher.
You can unhide it by removing the `#hotspot-section` and `#hotspot-selector`
![image](https://github.com/MinecraftJohn/wifi-connect/assets/84890923/1533fc41-c11f-41f2-8c83-fdb719e92547)

On the other side of sending data something like that, I don't have any idea how to do that I'm really sorry.

**Comment by zagub59** [comment]
Hi !
Thanks for your feedback :) I managed to perform a successfull form authentication but it's been a pain as the function is not implemented in the template HTML published by TP Link. I'm in the process of adapting index.html with your nice theme but the backend process is taken care of. 

I can post the added code here if you or someone else is interested but be kind as I'm not a programmer and thus, my code is probably far from the best way to do it (but it works for the time being !).

**Comment by MinecraftJohn** [comment]
Share it please, I like to learn about your email address thingy idea. Was your goal is instead of logging in the portal using voucher code you want your guest to login using email address? 🤔
